# Generated by Django 3.1.7 on 2021-03-07 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('starter', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reporter',
            options={'ordering': ['first_name']},
        ),
    ]
