name: test

on: [push, pull_request, workflow_dispatch]

jobs:
    test-job:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                python-version: [3.9]

        steps:
            - uses: actions/checkout@v2
            - name: Set up Python ${{ matrix.python-version }}
              uses: actions/setup-python@v2
              with:
                  python-version: ${{ matrix.python-version }}

            - uses: dschep/install-pipenv-action@v1
            - name: Install pipenv
              run: |
                  pip install pipenv
            - name: Install dependencies
              run: |
                  pipenv install --dev

            - name: Run checks
              run: |
                  pipenv run flake8 --statistics --show-source
                  pipenv run pytest django_graphene_starter
                  pipenv run python3 django_graphene_starter/manage.py check

            - name: Upload coverage to Codecov
              uses: codecov/codecov-action@v2
              with:
                  files: ./coverage.xml
                  directory: .
                  flags: unittests
                  name: codecov-umbrella
                  fail_ci_if_error: false
                  path_to_write_report: ./coverage/codecov_report.txt
                  verbose: true
